import"./assets/styles-JE8YjOlG.js";import{a}from"./assets/vendor-2s9xPmg-.js";const r={modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),productsList:document.querySelector(".products"),categoriesList:document.querySelector(".categories"),loadMoreBtn:document.querySelector(".load-more-btn"),notFound:document.querySelector(".not-found")};function y(t){const o=["All",...t].map(s=>`
    <li class="categories__item">
         <button class="categories__btn" type="button">${s}</button>
    </li>`).join("");return r.categoriesList.innerHTML=o}function n(t){const e=t.map(({id:o,thumbnail:s,title:u,brand:g,category:_,price:m})=>`
    <li class="products__item" data-id="${o}">
        <img class="products__image" src="${s}" alt="${u}"/>
        <p class="products__title">${u}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand: ${g}</span></p>
        <p class="products__category">Category: ${_}</p>
        <p class="products__price">Price: ${m}$</p>
    </li>`).join("");return r.productsList.insertAdjacentHTML("beforeend",e)}const f="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_ID:"/products/",PRODUCTS_BY_CATEGORY:"/products/category/",SEARCH:"/products/search"};a.defaults.baseURL=f;async function L(){return(await a.get(i.CATEGORIES)).data}async function l(t){const e={limit:12,skip:(t-1)*12};return(await a.get(i.PRODUCTS,{params:e})).data}async function C(t,e){const o={limit:12,skip:(e-1)*12};return(await a.get(`${i.PRODUCTS_BY_CATEGORY}${t}`,{params:o})).data}async function p(t,e){return e==="All"?await l(t):await C(e,t)}function d(t,e){e.currentPage*12>=t.total?r.loadMoreBtn.classList.add("is-hidden"):r.loadMoreBtn.classList.remove("is-hidden")}async function P(t){const e=await p(t.currentPage,t.category);console.log("handleloadMore",e),d(e,t),n(e.products)}async function b(t,e){if(!t.target.classList.contains("categories__btn"))return;document.querySelectorAll(".categories__btn").forEach(s=>s.classList.remove("categories__btn--active")),t.target.classList.add("categories__btn--active"),e.category=t.target.textContent,e.currentPage=1,r.productsList.innerHTML="";const o=await p(e.currentPage,e.category);o.products.length===0?r.notFound.classList.add("not-found--visible"):r.notFound.classList.remove("not-found--visible"),d(o,e),n(o.products)}const c={currentPage:1,category:"All"};S();A();r.loadMoreBtn.addEventListener("click",()=>{c.currentPage+=1,P(c)});r.categoriesList.addEventListener("click",t=>b(t,c));async function S(){const t=await L();y(t)}async function A(){const t=await l(c.currentPage);d(t,c),n(t.products)}
//# sourceMappingURL=index.js.map
